/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export { }

declare module 'vue' {
  export interface GlobalComponents {
    AppAutocomplete: typeof import('./src/components/app/Autocomplete.vue')['default']
    AppDialog: typeof import('./src/components/app/AppDialog.vue')['default']
    AppList: typeof import('./src/components/app/AppList.vue')['default']
    AppSelect: typeof import('./src/components/app/AppSelect.vue')['default']
    AppSheet: typeof import('./src/components/app/AppSheet.vue')['default']
    AppSnackbar: typeof import('./src/components/app/AppSnackbar.vue')['default']
    AppTextField: typeof import('./src/components/app/AppTextField.vue')['default']
    AppThemeToggle: typeof import('./src/components/app/AppThemeToggle.vue')['default']
    AppTooltipBtn: typeof import('./src/components/app/AppTooltipBtn.vue')['default']
    AppUploader: typeof import('./src/components/app/AppUploader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
